frame_id: bec352a8-0966-11ee-8e72-a02942aaea38
storage_directory: dev-media-cache
playlist_file: playlist.m3u
server: http://192.168.86.102:8080
poll_interval: 30
player_cmd:
  - cvlc
  - -f
  - --loop
  - --no-osd
