frame_id:  ee2551b6-0b1b-11ee-8e72-a02942aaea38
storage_directory: dev-media-cache
playlist_file: playlist.m3u
server: http://localhost:8080
poll_interval: 30
player_cmd:
  - cvlc
  - -f
  - --loop
  - --no-osd
