# Wide on the server
frame_id: ae6ee0aa-0a53-11ee-8e72-a02942aaea38
server: http://192.168.86.102:8080

# Local wide
# frame_id: 9c26c648-0b1a-11ee-8e72-a02942aaea38
# server: http://localhost:8080

# The following likely do not need to be changed
storage_directory: dev-media-cache
playlist_file: playlist.m3u
poll_interval: 300
player_cmd:
  - mplayer
  - -fs
  - -playlist
